
export const SAMPLE_CARDS = [
	{
		id: '1',
		question: 'The capital of Brunei is:',
		answer: 'Bandar Seri Begawan',
		options: ['Dhaka', 'Thimphu', 'Bandar Seri Begawan'],
	},
	{
		id: '2',
		question: 'The capital of Bangladesh is:',
		answer: 'Dhaka',
		options: ['Dhaka', 'Thimphu', 'Bandar Seri Begawan'],
	},
	{
		id: '3',
		question: 'The capital of Bhutan is:',
		answer: 'Thimphu',
		options: ['Dhaka', 'Thimphu', 'Bandar Seri Begawan'],
	},
	{
		id: '4',
		question: 'The capital of Singapore is:',
		answer: 'Singapore',
		options: ['Kathmandu', 'Singapore', 'Jakarta'],
	},
	{
		id: '5',
		question: 'The capital of Nepal is:',
		answer: 'Kathmandu',
		options: ['Kathmandu', 'Singapore', 'Jakarta'],
	},
	{
		id: '6',
		question: 'The capital of Indonesia is:',
		answer: 'Jakarta',
		options: ['Kathmandu', 'Singapore', 'Jakarta'],
	},
	{
		id: '7',
		question: 'The capital of Mongolia is:',
		answer: 'Ulaanbaatar',
		options: ['New Delhi', 'Tehran', 'Ulaanbaatar'],
	},
	{
		id: '8',
		question: 'The capital of India is:',
		answer: 'New Delhi',
		options: ['New Delhi', 'Tehran', 'Ulaanbaatar'],
	},
	{
		id: '9',
		question: 'The capital of Iran is:',
		answer: 'Tehran',
		options: ['New Delhi', 'Tehran', 'Ulaanbaatar'],
	},
	{
		id: '10',
		question: 'The capital of Pakistan is:',
		answer: 'Islamabad',
		options: ['Kabul', 'Islamabad', 'Tashkent'],
	},
	{
		id: '11',
		question: 'The capital of Afghanistan is:',
		answer: 'Kabul',
		options: ['Kabul', 'Islamabad', 'Tashkent'],
	},
	{
		id: '12',
		question: 'The capital of Uzbekistan is:',
		answer: 'Tashkent',
		options: ['Kabul', 'Islamabad', 'Tashkent'],
	},
	{
		id: '13',
		question: 'The capital of Thailand is:',
		answer: 'Bangkok',
		options: ['Vientiane', 'Bangkok', 'Bishkek'],
	},
	{
		id: '14',
		question: 'The capital of Laos is:',
		answer: 'Vientiane',
		options: ['Vientiane', 'Bangkok', 'Bishkek'],
	},
	{
		id: '15',
		question: 'The capital of Kyrgyzstan is:',
		answer: 'Bishkek',
		options: ['Vientiane', 'Bangkok', 'Bishkek'],
	},
	{
		id: '16',
		question: 'The capital of Cambodia is:',
		answer: 'Phnom Penh',
		options: ['Hanoi', 'Manila', 'Phnom Penh'],
	},
	{
		id: '17',
		question: 'The capital of Philippines is:',
		answer: 'Manila',
		options: ['Hanoi', 'Manila', 'Phnom Penh'],
	},
	{
		id: '18',
		question: 'The capital of Vietnam is:',
		answer: 'Hanoi',
		options: ['Hanoi', 'Manila', 'Phnom Penh'],
	},
	{
		id: '19',
		question: 'The capital of Taiwan is:',
		answer: 'Taipei City',
		options: ['Dushanbe', 'Dili', 'Taipei City'],
	},
	{
		id: '20',
		question: 'The capital of Tajikistan is:',
		answer: 'Dushanbe',
		options: ['Dushanbe', 'Dili', 'Taipei City'],
	},
	{
		id: '21',
		question: 'The capital of Timor-Leste is:',
		answer: 'Dili',
		options: ['Dushanbe', 'Dili', 'Taipei City'],
	},
	{
		id: '22',
		question: 'The capital of Sri Lanka is:',
		answer: 'Colombo',
		options: ['Malé', 'Kuala Lumpur', 'Colombo'],
	},
	{
		id: '23',
		question: 'The capital of the Maldives is:',
		answer: 'Malé',
		options: ['Malé', 'Kuala Lumpur', 'Colombo'],
	},
	{
		id: '24',
		question: 'The capital of Malaysia is:',
		answer: 'Kuala Lumpur',
		options: ['Malé', 'Kuala Lumpur', 'Colombo'],
	},
	{
		id: '25',
		question: 'The capital of Myanmar is:',
		answer: 'Naypyidaw',
		options: ['Malé', 'Kuala Lumpur', 'Naypyidaw'],
	},
]